### ISSUE TITLE
"No Module Named Error"

### ISSUE THREAD

**Issue by Onegarious** [sandsturm/whatsapp-converter#10]
Hi,

Thank your very much for your kind and laborious efforts followed by benevolent support.

However, I am getting the following errors:
a. If I use the commands as on the instructions [after successful installation of dependencies] I get:
"python: can't open file 'E:\pythonProject\whatsapp-converter-0.5.4\whatsapp_converter\whatsapp-converter.py': [Errno 2] No such file or directory"
I realized, it maybe because the file and folders are named with "-" instead of "-" prescribed in the instructions. So I changed them accordingly. But,
b. If I use the commands with "_" in the sames, I get
"ModuleNotFoundError: No module named 'whatsapp_converter.colors'; 'whatsapp_converter' is not a package" 

I tried googling for about 8 hours now but unfortunately I wasnt able to find any solution. So, I tried editing the code so as to rectify the issue. I was able to somewhat resolve the same but then, I am not getting any output whatsoever.

Request you to kindly help, please.

**Comment by sandsturm** [comment]
Hi Onegarious, 

Based on the path provided, I assume you are using Windows. Did you install whatsapp-converter by cloning the GitHub repository or by running "pip install whatsapp-converter"?

**Comment by sandsturm** [comment]
Can you please provide more information? Otherwise, I will close this topic tomorrow.

**Comment by Onegarious** [comment]
Hi, sorry for the delay in responding. I was out of city. 

Yes, I downloaded the folder and created a project. Which is why I Guess I was getting the error .However, due to urgency in submission of project took inspiration from your code and made my own script. 

Nonetheless, I am still interested to know the solution please in case of future projects.

**Comment by sandsturm** [comment]
Yes, sure. Can you please execute the pip install again and post the output here?

**Comment by Onegarious** [comment]
Hi, it is working fine after installing through pip. thanks a lot. Again, Really Sincerely Sorry for the delayed reply.

**Comment by sandsturm** [comment]
Very good, I'm glad to hear that! Don't worry, I'm always interested in improving the application.

Did you also use pip the first time or cloned the repository?
