### ISSUE TITLE
I cant use this Converter in Jupyter notebook

### ISSUE THREAD

**Issue by hippiemeraki** [sandsturm/whatsapp-converter#12]
I used the below code and the error appeared!

import whatsapp_converter
whatsapp_converter.convert(filename="WhatsApp.txt",resultset="Whats.xlsx")

AttributeError                            Traceback (most recent call last)
[<ipython-input-15-db414c0d69bd>](https://localhost:8080/#) in <module>()
----> 1 whatsapp_converter.convert(filename="WhatsApp.txt",resultset="Whats.xlsx")

AttributeError: module 'whatsapp_converter' has no attribute 'convert'

**Comment by sandsturm** [comment]
Hi @hippiemeraki, it took some time to fix this because I had a lot to do at work. Now it should work, v0.6.0. Can you please check? PyPi is updated as well.

**Comment by sandsturm** [comment]
Any feedback or should I close the issue?

**Comment by hippiemeraki** [comment]
Please guide me through this.
In Jupyter notebook how will we use it?

**Comment by sandsturm** [comment]
Like you already mentioned in your initial post:

```
!pip install whatsapp-converter 
import whatsapp_converter
whatsapp_converter.convert(filename="WhatsApp.txt",resultset="Whats.xlsx")
```
Make sure you have the WhatsApp.txt in the same folder as the Jupyter workbook.

**Comment by hippiemeraki** [comment]
Ok, will do that.

**Comment by sandsturm** [comment]
Due to the security risk, the first command (!pip) only works on certain Jupyter instances or on local instances.
