### ISSUE TITLE
Appears not to work with messages including newline

### ISSUE THREAD

**Issue by ValerioGiuffrida** [sandsturm/whatsapp-converter#13]

**Comment by sandsturm** [comment]
Correct, that is a bug. I fixed it and pushed the latest version 0.6.1 to GitHub and PyPi. If you have time, can you update your installation and check it?

**Comment by sandsturm** [comment]
Any feedback or should I close the issue?

**Comment by ValerioGiuffrida** [comment]
Thanks for the quick reply! I installed the latest and it is working!

**Comment by sandsturm** [comment]
Thanks!
