### ISSUE TITLE
Error when the user exporting whatsapp chat has a 24hr clock format

### ISSUE THREAD

**Issue by atharvawaghmare14** [sandsturm/whatsapp-converter#5]
The program gives error when the chat exporting device uses a 24 hr clock format. That is because the exported chat outline from a device with 12hr clock is different from 24hr format. 
1. There is no AM PM in the 24hr export.
2. The date pattern in 24hr is different from 12 hr format export.
The entire program crashes due to this flaws
Please debug this as soon as possible.

**Comment by sandsturm** [comment]
Sure. Can you please provide an anonymized export? I will have a look on this.

**Comment by atharvawaghmare14** [comment]
> Sure. Can you please provide an anonymized export? I will have a look on this.

[dataset2.txt](https://github.com/sandsturm/whatsapp-converter/files/6568079/dataset2.txt)
 This is the export I was getting errors with.

**Comment by sandsturm** [comment]
I corrected it in v0.4.4 and updated it here and in PyPi. Can you give it a try?

**Comment by atharvawaghmare14** [comment]
> I corrected it in v0.4.4 and updated it here and in PyPi. Can you give it a try?

sure thanks! it worked
