### ISSUE TITLE
No iOS whatsapp export compatibility

### ISSUE THREAD

**Issue by atharvawaghmare14** [sandsturm/whatsapp-converter#6]
The program cannot convert whatsapp chat export from an iOS device to CSV. I have attached a sample chat export with this message.
[Uploading chem_data.txt…]()

**Comment by sandsturm** [comment]
Thank you for your email. Can you please try to upload the attachment again?

**Comment by atharvawaghmare14** [comment]
[ank_chem_nospam.txt](https://github.com/sandsturm/whatsapp-converter/files/6648976/ank_chem_nospam.txt)

**Comment by sandsturm** [comment]
Hi. What exactly is the issue? I just tried it and it converts your provided file perfectly into a CSV file.

**Comment by sandsturm** [comment]
Hi, any update here or should I close the issue?

**Comment by atharvawaghmare14** [comment]
Can you please recheck with this data i've attached. it is giving me errors. This is an export from an iphone.
<deleted>

**Comment by sandsturm** [comment]
Hi. I downloaded and deleted your attachment because it contained cell phone numbers.

Yes, it produced an error. I updated whatsapp-converter to **v0.5.4**, now it works. Please give it a try. I would be glad if you could provide feedback if everything is working now. Thanks a lot.

**Comment by sandsturm** [comment]
Did you check, can I close the issue? Happy to help, but I would need some feedback.
