### ISSUE TITLE
Separates long messages when a new line/paragraph is detected

### ISSUE THREAD

**Issue by ankitts** [sandsturm/whatsapp-converter#7]
There's a bug in conversion of long messages. The long messages with more than one paragraphs or whenever a new line is detected in a message(in a message typed by hitting tab/enter at least once) , it displays the later part of message in a new row in both csv & xls format. The whole message no matter how big it is, it should come in a single cell/row.

**Comment by sandsturm** [comment]
Thank you, I will have a look at it. I thought I covered this in the code ...

**Comment by sandsturm** [comment]
Okay, you are right 😁 I prepared a switch but did not implement the code. Let me check the effort.

**Comment by sandsturm** [comment]
I have updated the github and pypi packages. Now by default multi-line paragraphs are merged into one line of the export. There is a new command line parameter "-n" to have the old behavior that multi-line paragraphs are split into separate lines in the export. 

Can you check the new version and provide feedback if it is now the requested behavior?

**Comment by ankitts** [comment]
Yeah, it works perfectly now!

Thanks a lot for the effort.😊

**Comment by sandsturm** [comment]
Thank you for requesting it. It is always a motivation ...
