### ISSUE TITLE
issue with datetime

### ISSUE THREAD

**Issue by gryshkoff** [sandsturm/whatsapp-converter#9]
chat,txt contains data on english and ukrainian language

C:\Python\Lib\site-packages\whatsapp_converter>python whatsapp_converter.py chat.txt chat.csv
Converting data now
  0%|                                                                                          | 0/1584 [00:00<?, ?it/s]  0%|▏                                                                                         | 4/1584 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Python\Lib\site-packages\whatsapp_converter\whatsapp_converter.py", line 226, in <module>
    convert(filename=args.filename, resultset=args.resultset, verbose=args.verbose, debug=args.debug)
  File "C:\Python\Lib\site-packages\whatsapp_converter\whatsapp_converter.py", line 191, in convert
    csv.write(dataset[1] + ' ' + dataset[2] + '|' + dataset[1] + '|' + dataset[2] + '|' + dataset[3] + '|' + dataset[4] + '\n')
TypeError: unsupported operand type(s) for +: 'datetime.date' and 'str'

**Comment by sandsturm** [comment]
Can you please attach an anonymized export of the chat? I once had an export of a Russian chat and it converted the chat without problems.

**Comment by gryshkoff** [comment]
Thanks for your reply, if possible, please describe step by step, I'm not
quite a confident python user

Thank you!

Downloaded and deleted the message

**Comment by sandsturm** [comment]
Hmmm. It works perfectly on my computer, I got a clean export. Did you use pip to install the whatsapp-converter package?

What you could try (if chat.txt is inside the whatsapp_converter directory):
```
cd ..
python -m whatsapp_converter whatsapp_converter/chat.txt chat.csv
```

**Comment by gryshkoff** [comment]
Yes, I did.
i  used next link

https://pypi.org/project/whatsapp-converter/#description

ср, 23 июн. 2021 г. в 13:17, Martin Sand ***@***.***>:

**Comment by sandsturm** [comment]
Can you please check the python version? It works only with python3:

`python --version`

**Comment by gryshkoff** [comment]
Just used your command  Convert WhatsApp TXT to CSV (Default Use Case)
No CSV file was created , and were it must be generated, same path?

C:\Python\Lib\site-packages\whatsapp_converter>whatsapp_converter.py
chat.txt
Converting data now
100%|█████████████████████████████████████████████████████████████████████████|
20843/20843 [00:00<00:00, 115221.18it/s]
Wrote 20665 lines


Also your command has name python whatsapp*-*converter.py
  and filename is  whatsapp*_*converter.py


ср, 23 июн. 2021 г. в 13:20, Dmitriy Hryshkov ***@***.***>:

**Comment by sandsturm** [comment]
So it worked? The default file is saved in the same directory as the whatsapp-converter. It is called **result.csv**.

**Comment by gryshkoff** [comment]
No, it didn't. [image: image.png]
No CSV created

ср, 23 июн. 2021 г. в 13:42, Martin Sand ***@***.***>:

**Comment by sandsturm** [comment]
> Also your command has name python whatsapp*-*converter.py and filename is  whatsapp*_*converter.py

If you installed whatsapp-converter via pip, than you could just start it from the command line without the .py extension. See here:

```
(env) [tmp]$ whatsapp-converter example-cyrillic result.csv
Reading import file
Converting data now
100%|████████████████████████████████████████████████████████████████████████████| 2813/2813 [00:00<00:00, 64412.56it/s]
Writing to result.csv
Wrote 2746 lines
```

**Comment by gryshkoff** [comment]
[image: image.png]
[image: image.png]

no CSV IS CREATED
where must stay export.txt?


ср, 23 июн. 2021 г. в 13:52, Martin Sand ***@***.***>:

**Comment by sandsturm** [comment]
Sorry, the pictures are not attached. I think you need to upload and attach them here in the chat.

> where must stay export.txt?

It does not matter. Typically in the same directory where you execute the whatsapp-converter command. Alternatively you can provide an absolute path, e.g. `/tmp/export.txt` on a Linux system.

**Comment by gryshkoff** [comment]
Ср, 23 июня 2021 г. в 14:10, Martin Sand ***@***.***>:

**Comment by gryshkoff** [comment]
so i did not get any result as you can see on screenshot of commandline


ср, 23 июн. 2021 г. в 14:13, Dmitriy Hryshkov ***@***.***>:

**Comment by gryshkoff** [comment]
![photo_2021-06-23_15-23-13](https://user-images.githubusercontent.com/86348593/123095717-08271180-d437-11eb-8130-b0a6a6143655.jpg)
NO "writing result.csv"

**Comment by sandsturm** [comment]
For sure you are using an old version of the converter because the `-n` argument is not shown. Can you please upgrade the application via pip? Maybe this helps.

`pip install --upgrade whatsapp_converter`

**Comment by gryshkoff** [comment]
[update log.txt](https://github.com/sandsturm/whatsapp-converter/files/6701974/update.log.txt)

**Comment by sandsturm** [comment]
Can you please check that you have python3 installed?

`python --version`

**Comment by gryshkoff** [comment]
of course , i have latest python 3.9.5 
Almost solved , i  mannualy downloaded files and replaced , now i have - n argument (pip install --upgrade whatsapp_converter did not help )
Now situation like this, i cant find resultset.csv
![image](https://user-images.githubusercontent.com/86348593/123102210-7e2e7700-d43d-11eb-856c-796e33130299.png)

**Comment by gryshkoff** [comment]
Solved ,the result is saved to the desktop in the whatsapp-converter-0.5.4 folder that I accidentally added there.
Thank you for support!

**Comment by sandsturm** [comment]
Perfect, happy to hear that!
